packaging_format = 2

id = "spip"
name = "SPIP"
description.en = "CMS with a focus on collaborative edition and multilingualism"
description.fr = "CMS conçu pour l'édition collaborative et le multilinguisme"

version = "4.2.2~ynh1"

maintainers = ["cyp"]

[upstream]
license = "GPL-3.0-or-later"
website = "http://www.spip.net/"
demo = "https://demo.spip.net/"
admindoc = "https://www.spip.net/en_rubrique209.html"
userdoc = "https://www.spip.net/en_rubrique57.html"
code = "https://git.spip.net/spip/spip"
cpe = "???" # FIXME: optional but recommended if relevant, this is meant to contain the Common Platform Enumeration, which is sort of a standard id for applications defined by the NIST. In particular, Yunohost may use this is in the future to easily track CVE (=security reports) related to apps. The CPE may be obtained by searching here: https://nvd.nist.gov/products/cpe/search. For example, for Nextcloud, the CPE is 'cpe:2.3:a:nextcloud:nextcloud' (no need to include the version number)
fund = "???" # FIXME: optional but recommended (or remove if irrelevant / not applicable). This is meant to be an URL where people can financially support this app, especially when its development is based on volunteers and/or financed by its community. YunoHost may later advertise it in the webadmin.

[integration]
yunohost = ">= 4.3.2"
architectures = "all" # FIXME: can be replaced by a list of supported archs using the dpkg --print-architecture nomenclature (amd64/i386/armhf/arm64), for example: ["amd64", "i386"]
multi_instance = true
ldap = "?" # FIXME: replace with true, false, or "not_relevant". Not to confuse with the "sso" key : the "ldap" key corresponds to wether or not a user *can* login on the app using its YunoHost credentials.
sso = "?" # FIXME: replace with true, false, or "not_relevant". Not to confuse with the "ldap" key : the "sso" key corresponds to wether or not a user is *automatically logged-in* on the app when logged-in on the YunoHost portal.
disk = "50M" # FIXME: replace with an **estimate** minimum disk requirement. e.g. 20M, 400M, 1G, ...
ram.build = "50M" # FIXME: replace with an **estimate** minimum ram requirement. e.g. 50M, 400M, 1G, ...
ram.runtime = "50M" # FIXME: replace with an **estimate** minimum ram requirement. e.g. 50M, 400M, 1G, ...

[install]
    [install.domain]
    # this is a generic question - ask strings are automatically handled by Yunohost's core
    type = "domain"

    [install.path]
    # this is a generic question - ask strings are automatically handled by Yunohost's core
    type = "path"
    default = "/spip"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.admin]
    # this is a generic question - ask strings are automatically handled by Yunohost's core
    type = "user"

    [install.password]
    # this is a generic question - ask strings are automatically handled by Yunohost's core
    type = "password"

    [install.users_status]
    ask.en = "Choose the status of YunoHost users"
    ask.fr = "Choisissez le status des utilisateurs de YunoHost"
    type = "string"
    choices = ["Administrator", "Editor", "Visitor"]
    default = "Editor"

[resources]
        [resources.sources.main]
        url = "https://files.spip.net/spip/archives/spip-v4.2.2.zip"
        sha256 = "47ab43b1ac8014b70e60867ecd9474a2afeaff471852eab0f41b94cb077d18d1"
        in_subdir = false


    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.database]
    type = "mysql"
